env:
  browser: true
  serviceworker: true
  es2020: true
extends: "eslint:recommended"
parserOptions:
  ecmaVersion: 11
rules:
  no-unreachable-loop:
    - error
  curly:
    - error
    - multi-line
  dot-location:
    - error
    - property
  eqeqeq:
    - error
    - always
  dot-notation:
    - error
  no-eval:
    - error
  no-implicit-coercion:
    - error
  no-labels:
    - error
  no-multi-spaces:
    - error
  no-new:
    - error
  no-param-reassign:
    - warn
  no-return-assign:
    - error
  no-sequences:
    - warn
  no-throw-literal:
    - error
  no-unused-expressions:
    - error
  no-useless-return:
    - error
  yoda:
    - error
    - never
  strict:
    - error
    - global
  no-shadow:
    - error
  array-bracket-newline:
    - error
    - consistent
  array-bracket-spacing:
    - error
    - never
  array-element-newline:
    - error
    - consistent
  block-spacing:
    - error
    - always
  brace-style:
    - error
    - 1tbs
  capitalized-comments:
    - error
    - always
  comma-dangle:
    - error
    - only-multiline
  comma-spacing:
    - error
    - before: false
      after: true
  comma-style:
    - error
    - last
  computed-property-spacing:
    - error
    - never
  eol-last:
    - error
    - always
  func-call-spacing:
    - error
    - never
  func-names:
    - off
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  function-call-argument-newline:
    - error
    - consistent
  id-match:
    - error
    - "^_{0,2}([a-z_]+[a-z]|[a-z_])$"
  implicit-arrow-linebreak:
    - error
    - beside
  indent:
    - error
    - 4
    - SwitchCase: 1
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
      mode: strict
  keyword-spacing:
    - error
    - before: true
      after: true
  line-comment-position:
    - error
    - position: beside
      ignorePattern: "@ts"
      applyDefaultIgnorePatterns: true
  linebreak-style:
    - error
    - unix
  multiline-comment-style:
    - error
    - starred-block
  multiline-ternary:
    - error
    - never
  new-parens:
    - error
    - always
  newline-per-chained-call:
    - error
  no-lonely-if:
    - error
  no-mixed-operators:
    - error
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 0
      maxBOF: 0
  no-nested-ternary:
    - error
  no-tabs:
    - error
  no-trailing-spaces:
    - error
  no-unneeded-ternary:
    - error
  no-unused-vars:
    - warn
  no-useless-concat:
    - error
  no-whitespace-before-property:
    - error
  object-curly-newline:
    - error
    - multiline: true
  object-curly-spacing:
    - error
    - never
  one-var:
    - error
    - initialized: never
  operator-assignment:
    - error
    - always
  operator-linebreak:
    - error
    - after
  padded-blocks:
    - error
    - never
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: "*"
      next: return
    - blankLine: never
      prev: block-like
      next: return
  prefer-exponentiation-operator:
    - error
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - double
  semi:
    - error
    - never
  space-before-blocks:
    - error
    - always
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
  space-in-parens:
    - error
    - never
  space-infix-ops:
    - error
  space-unary-ops:
    - error
  spaced-comment:
    - error
    - always
  switch-colon-spacing:
    - error
    - after: true
      before: false
  template-tag-spacing:
    - error
    - never
  unicode-bom:
    - error
    - never
  arrow-parens:
    - error
    - as-needed
  arrow-spacing:
    - error
    - before: true
      after: true
  no-var:
    - error
  object-shorthand:
    - error
    - always
  prefer-const:
    - warn
  prefer-numeric-literals:
    - error
  prefer-template:
    - error
